CREATE DATABASE IF NOT EXISTS R3;
USE R3;
# ===========================================================================
SELECT PERSON.ID AS PERSON_ID, VORNAME, NACHNAME,
       PERSONAL_AUSWEIS.ID AS PA_ID, NUMMER, AUSGESTELLT, GÜLTIG
FROM PERSON LEFT JOIN PERSONAL_AUSWEIS ON PERSON.ID = PERSONAL_AUSWEIS.PERSON_ID;

CREATE VIEW PERSON_PA AS
SELECT PERSON.ID AS PERSON_ID, VORNAME, NACHNAME,
       PERSONAL_AUSWEIS.ID AS PA_ID, NUMMER, AUSGESTELLT, GÜLTIG
FROM PERSON LEFT JOIN PERSONAL_AUSWEIS ON PERSON.ID = PERSONAL_AUSWEIS.PERSON_ID;

SELECT * FROM PERSON_PA;